IBX-8175: OpenAPI compatible move user group endpoint
ibexa/rest pull request #108
Opened 2024-06-24 16:31 UTC by barw4

| :ticket: Issue | IBX-8175 |
|----------------|-----------|

#### Related PRs: 
https://github.com/ibexa/rest/pull/107

#### Description:
The new endpoint follows the given specification:
```
POST /api/v2/ibexa/user/groups/1/5/235
Content-Type: application/vnd.ibexa.api.MoveUserGroupInput+json
Accept: application/json
{
    "MoveUserGroupInput": {
        "destination": "/1/5/14"
    }
}
```

#### Documentation:
TBD

2024-07-01 07:20 UTC, konradoboza approved these changes

2024-07-01 07:20 UTC, konradoboza commented on src/lib/Server/Validation/Builder/Input/Parser/MoveUserGroupInputValidatorBuilder.php
> +class MoveUserGroupInputValidatorBuilder extends BaseInputParserValidatorBuilder
```suggestion
final class MoveUserGroupInputValidatorBuilder extends BaseInputParserValidatorBuilder
```

2024-07-03 07:35 UTC, webhdx approved these changes

2024-07-23 11:48 UTC, micszo requested changes
Here also 404 is returned instead of 403 when destination does not exist. :)

ref. https://doc.ibexa.co/en/latest/api/rest_api/rest_api_reference/rest_api_reference.html#managing-users-move-user-group

2024-07-24 10:09 UTC, micszo approved these changes
QA Approved on Ibexa Commerce 5.0.x-dev.

2024-07-24 16:04 UTC, merged